/**
 * GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Produced by `npm run gen-schema` from data/*.fragment.json and the
 * interaction-model enums in src/srs/evidence.ts.
 *
 * Hand-edits are destroyed on the next generation and, worse, temporarily hide
 * the drift that test/gen-schema.test.ts exists to catch.
 */

/** Every reviewable component, in taxonomy order. */
export const LEAF_IDS = [
  'NOM.gender.masc_fem_o',
  'NOM.gender.comu',
  'NOM.gender.ista',
  'NOM.gender.suppletive',
  'NOM.gender.suffix_essa',
  'NOM.gender.suffix_or',
  'NOM.gender.suffix_riu',
  'NOM.gender.diverge_fr',
  'NOM.gender.invariable',
  'NOM.number.regular',
  'NOM.number.sibilant',
  'NOM.number.a_es',
  'NOM.number.hidden_n',
  'NOM.number.stressed_vowel',
  'NOM.number.invariable',
  'NOM.number.pluralia_tantum',
  'NOM.adj.four_form',
  'NOM.adj.two_form',
  'NOM.adj.invariable',
  'NOM.adj.position',
  'NOM.adj.agree.coord',
  'NOM.deriv.dimin',
  'NOM.deriv.augment',
  'NOM.deriv.agent_dor',
  'NOM.deriv.agent_er',
  'NOM.deriv.abstract_esa',
  'NOM.deriv.abstract_tat',
  'NOM.deriv.abstract_ment',
  'NOM.deriv.ista',
  'NOM.comp.verb_nom',
  'ART.def.forma.paradigma',
  'ART.def.forma.elisio',
  'ART.def.forma.la_no_elisio',
  'ART.def.forma.el_iod',
  'ART.def.us.abans_possessiu',
  'ART.def.us.dates_setmana',
  'ART.def.us.hores',
  'ART.def.us.anys',
  'ART.def.us.paisos',
  'ART.def.us.llengues',
  'ART.def.us.titols',
  'ART.def.us.toponims',
  'ART.indef.paradigma',
  'ART.indef.plural',
  'ART.indef.uns_unes_aproximacio',
  'ART.indef.uns_unes_pairs',
  'ART.indef.omissio_atribut',
  'ART.indef.sense_partitiu',
  'ART.indef.omissio_negacio',
  'ART.personal.en',
  'ART.personal.na',
  'ART.personal.n_elisio',
  'ART.personal.la_alternativa',
  'ART.personal.absencia',
  'ART.personal.contraccio',
  'ART.contract.al',
  'ART.contract.als',
  'ART.contract.del',
  'ART.contract.dels',
  'ART.contract.pel',
  'ART.contract.pels',
  'ART.contract.no_contraccio_elisio',
  'ART.contract.cap_al',
  'ART.salat.es_sa',
  'ART.salat.plural',
  'ART.salat.elisio',
  'VERB.ind.imperfet',
  'VERB.ind.passat_perifrastic',
  'VERB.perf.present',
  'VERB.conj.3.incoatiu',
  'VERB.mod.obligacio',
  'VERB.ser_estar',
  'PRON.fort.subjecte',
  'PRON.feble.en',
  'PRON.feble.hi',
  'PRON.feble.combinacio.ci_cd',
  'DET.ordre_intern',
  'DET.dem.forma_paradigma',
  'DET.dem.deixi_espacial',
  'DET.dem.deixi_discursiva',
  'DET.poss.forma_paradigma',
  'DET.poss.aton',
  'DET.poss.nu_lexical',
  'DET.poss.posposat',
  'DET.poss.tercera_persona',
  'DET.poss.inalienable',
  'DET.quant.juncio_nominal',
  'DET.quant.grau.concordanca',
  'DET.quant.grau.prou_bastant',
  'DET.quant.polaritat.cap',
  'DET.quant.polaritat.gens',
  'DET.quant.polaritat.gaire',
  'DET.quant.polaritat.algun',
  'DET.quant.polaritat.qualsevol',
  'DET.quant.polaritat.contextos',
  'DET.quant.universal.tot',
  'DET.quant.universal.cada',
  'DET.quant.universal.dual',
  'DET.identitat.mateix_identitat',
  'DET.identitat.mateix_emfatic',
  'DET.identitat.altres_nu',
  'DET.identitat.aproximatius',
  'DET.num.cardinals_concordanca',
  'DET.num.sistema_decimal',
  'DET.num.ordinals',
  'DET.interrogatiu.quin',
  'DET.interrogatiu.quant',
  'PREP.atones.inventari',
  'PREP.atones.elisio_de',
  'PREP.atones.de_origen',
  'PREP.atones.amb',
  'PREP.atones.amb_mitja',
  'PREP.a_en.lloc.a_lloc',
  'PREP.a_en.lloc.en_sense_definit',
  'PREP.a_en.lloc.toponims',
  'PREP.a_en.temps.hores',
  'PREP.a_en.temps.parts_del_dia',
  'PREP.a_en.temps.data_sense_prep',
  'PREP.a_en.temps.durada',
  'PREP.per_pera.causa',
  'PREP.per_pera.agent',
  'PREP.per_pera.recorregut',
  'PREP.per_pera.temps_aproximat',
  'PREP.per_pera.finalitat_nominal',
  'PREP.per_pera.finalitat_infinitiu',
  'PREP.formes_no_finites.inf_regit_a',
  'PREP.formes_no_finites.inf_regit_de',
  'PREP.formes_no_finites.adjectiu_de',
  'PREP.formes_no_finites.sense',
  'PREP.formes_no_finites.abans_despres',
  'PREP.formes_no_finites.en_temporal',
  'PREP.formes_no_finites.en_gerundi',
  'PREP.regim.convergent',
  'PREP.regim.divergent_en',
  'PREP.regim.divergent_amb',
  'PREP.regim.divergent_de',
  'PREP.regim.caiguda_davant_que',
  'PREP.marcatge.cd_sense_prep',
  'PREP.marcatge.datiu_a',
  'PREP.marcatge.a_pronom_tonic',
  'PREP.marcatge.de_quantitatiu',
  'PREP.toniques.inventari',
  'PREP.toniques.locucions_amb_a',
  'PREP.toniques.des_de_punt',
  'PREP.toniques.des_de_fa',
  'PREP.toniques.locucions_amb_de',
  'CONJ.coord.copulativa',
  'CONJ.coord.ni',
  'CONJ.coord.disjuntiva',
  'CONJ.coord.distributiva',
  'CONJ.coord.adversativa.pero',
  'CONJ.coord.adversativa.sino',
  'CONJ.coord.adversativa.si_no',
  'CONJ.coord.illativa',
  'CONJ.coord.explicativa',
  'CONJ.completiva.que',
  'CONJ.completiva.interrogativa_indirecta',
  'CONJ.causal.perque',
  'CONJ.causal.com_que',
  'CONJ.causal.ja_que',
  'CONJ.final.perque_subjuntiu',
  'CONJ.final.per_tal_que',
  'CONJ.concessiva.encara_que',
  'CONJ.concessiva.tot_i_que',
  'CONJ.concessiva.per_molt_que',
  'CONJ.condicional.si',
  'CONJ.condicional.locucions',
  'CONJ.condicional.exceptiva',
  'CONJ.temporal.quan',
  'CONJ.temporal.mentre',
  'CONJ.temporal.abans_despres',
  'CONJ.temporal.locucions',
  'CONJ.manera.com',
  'CONJ.manera.com_si',
  'CONJ.manera.sense_que',
  'CONJ.comparativa.igualtat_desigualtat',
  'CONJ.comparativa.correlativa',
  'CONJ.consecutiva',
  'NEG.simple.no',
  'NEG.simple.pas',
  'NEG.concordanca.postverbal',
  'NEG.concordanca.preverbal',
  'NEG.concordanca.matriu_subordinada',
  'NEG.concordanca.minimitzadors',
  'NEG.aspecte.ja_no',
  'NEG.aspecte.encara_no',
  'NEG.aspecte.no_mes',
  'NEG.expletiu',
  'NEG.anticipada',
  'NEG.fragment',
  'NEG.abast_constituent',
  'NEG.restrictiva',
  'NEG.no_finita',
] as const;

export type ComponentId = (typeof LEAF_IDS)[number];

/**
 * One entry in the decomposition. LANGUAGE-INVARIANT: a component ID, the
 * Catalan surface form, and optionally its pronunciation. No French here; the
 * answer field carries all of it.
 */
export const COMPONENT_ENTRY_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['id', 'ca'],
  properties: {
    id: { type: 'string', enum: LEAF_IDS },
    ca: { type: 'string', minLength: 1 },
    ipa: { type: 'string', minLength: 1 },
  },
} as const;

/**
 * The decomposition payload. All five intents emit this same shape; only the
 * prompt and the surrounding logged fields differ.
 */
export const DECOMPOSITION_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['decomposition', 'answer', 'answer_lang'],
  properties: {
    decomposition: { type: 'array', items: COMPONENT_ENTRY_SCHEMA },
    answer: { type: 'string', minLength: 1 },
    answer_lang: { type: 'string', enum: ['fr'] },
  },
} as const;

/**
 * A logged query: the decomposition payload plus the interaction-model triple.
 *
 * `rating` is required exactly when `evidence` is the one type that
 * EVIDENCE_EFFECTS marks as requiring one, and forbidden otherwise. The
 * conditional is generated from that table rather than written by hand.
 */
export const QUERY_LOG_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: [
    'asked_at',
    'question',
    'intent',
    'direction',
    'evidence',
    'decomposition',
    'answer',
    'answer_lang',
  ],
  properties: {
    asked_at: { type: 'integer', minimum: 0 },
    question: { type: 'string', minLength: 1 },
    intent: {
      type: 'string',
      enum: ['comprehend', 'produce', 'teach', 'assess', 'pronounce'],
    },
    direction: { type: 'string', enum: ['ca_to_fr', 'fr_to_ca'] },
    evidence: { type: 'string', enum: ['lookup', 'recall', 'graded'] },
    rating: { type: 'string', enum: ['again', 'hard', 'good', 'easy'] },
    decomposition: DECOMPOSITION_SCHEMA.properties.decomposition,
    answer: DECOMPOSITION_SCHEMA.properties.answer,
    answer_lang: DECOMPOSITION_SCHEMA.properties.answer_lang,
  },
  allOf: [
    {
      if: {
        properties: { evidence: { enum: ['graded'] } },
        required: ['evidence'],
      },
      then: { required: ['rating'] },
      else: { not: { required: ['rating'] } },
    },
  ],
} as const;
